# Generated by Django 4.0.2 on 2022-02-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_age_user_country_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
